export const dummyResult = {
  fmaLeScore: 24,
  severity: 'Moderate',
  classification: 'CVA',
  confidence: 0.91,
  heelStrikeCount: 32,
  toeOffCount: 31,
  semiogram: {
    V: 0.82,
    StrT: 0.61,
    UtrT: 0.44,
    LDLJa: -2.15,
    SPARCrot: -1.78,
    CVStrT: 8.2,
    CVdstT: 7.5,
    P1acc: 0.72,
    P2acc: 0.68,
    SteL: 0.51,
    RMSaML: 1.24,
    iHRaAP: 87,
    iHRaCC: 82,
    iHRaML: 79,
    P1P2acc: 0.91,
    swTr: 0.96,
    dstT: 6.4,
  },
};

export const dummySessions = [
  {
    id: 'session-001',
    date: '12 March 2026',
    classification: 'CVA',
    severity: 'Moderate',
    fmaLeScore: 24,
    symmetry: 82,
  },
  {
    id: 'session-002',
    date: '05 March 2026',
    classification: 'Post-Op Recovery',
    severity: 'Mild',
    fmaLeScore: 29,
    symmetry: 91,
  },
  {
    id: 'session-003',
    date: '28 Feb 2026',
    classification: 'Initial Assessment',
    severity: 'Severe',
    fmaLeScore: 12,
    symmetry: 64,
  },
];
