import '../../data/models/gait_result.dart';
import '../../data/models/gait_session.dart';
import '../../data/models/semiogram_result.dart';

final SemiogramResult dummySemiogram = SemiogramResult(
  v: 0.82,
  strT: 0.71,
  utrT: 0.65,
  ldlja: 0.88,
  sparcrot: 0.74,
  sparctra: 0.69,
  sparcver: 0.72,
  mdifAP: 0.58,
  mdifML: 0.61,
  cvStrideTime: 0.42,
  cvStrideLength: 0.45,
  symmetryIndex: 0.82,
  stepLengthLeft: 0.52,
  stepLengthRight: 0.54,
  stanceLeft: 62.0,
  stanceRight: 60.0,
  cadence: 102.0,
);

final GaitResult dummyResult = GaitResult(
  fmaLeScore: 24,
  severity: 'Moderate',
  classification: 'CVA',
  confidence: 0.91,
  heelStrikeCount: 32,
  toeOffCount: 31,
  semiogram: dummySemiogram,
);

final List<GaitSession> dummySessions = [
  GaitSession(
    id: 's1',
    date: DateTime(2026, 3, 12),
    classification: 'CVA',
    severity: 'Moderate',
    result: GaitResult(
      fmaLeScore: 24,
      severity: 'Moderate',
      classification: 'CVA',
      confidence: 0.91,
      heelStrikeCount: 32,
      toeOffCount: 31,
      semiogram: dummySemiogram,
    ),
  ),
  GaitSession(
    id: 's2',
    date: DateTime(2026, 3, 5),
    classification: 'Post-Op Recovery',
    severity: 'Mild',
    result: GaitResult(
      fmaLeScore: 29,
      severity: 'Mild',
      classification: 'Post-Op Recovery',
      confidence: 0.87,
      heelStrikeCount: 38,
      toeOffCount: 37,
      semiogram: SemiogramResult(
        v: 0.95,
        strT: 0.82,
        utrT: 0.78,
        ldlja: 0.91,
        sparcrot: 0.85,
        sparctra: 0.80,
        sparcver: 0.83,
        mdifAP: 0.70,
        mdifML: 0.72,
        cvStrideTime: 0.31,
        cvStrideLength: 0.33,
        symmetryIndex: 0.91,
        stepLengthLeft: 0.58,
        stepLengthRight: 0.60,
        stanceLeft: 58.0,
        stanceRight: 57.0,
        cadence: 110.0,
      ),
    ),
  ),
  GaitSession(
    id: 's3',
    date: DateTime(2026, 2, 28),
    classification: 'Initial Assessment',
    severity: 'Severe',
    result: GaitResult(
      fmaLeScore: 12,
      severity: 'Severe',
      classification: 'Initial Assessment',
      confidence: 0.78,
      heelStrikeCount: 22,
      toeOffCount: 20,
      semiogram: SemiogramResult(
        v: 0.55,
        strT: 0.48,
        utrT: 0.42,
        ldlja: 0.64,
        sparcrot: 0.51,
        sparctra: 0.46,
        sparcver: 0.50,
        mdifAP: 0.38,
        mdifML: 0.40,
        cvStrideTime: 0.62,
        cvStrideLength: 0.65,
        symmetryIndex: 0.64,
        stepLengthLeft: 0.38,
        stepLengthRight: 0.44,
        stanceLeft: 70.0,
        stanceRight: 65.0,
        cadence: 84.0,
      ),
    ),
  ),
];
